### List all messages
GET http://localhost:3000/messages


### Get a message
GET http://localhost:3000/messages/123


### Create a new messages
POST http://localhost:3000/messages
Content-Type: application/json

{
    "content": "Hi there"
}